# Created by: Matthias Breddin <mb@lunetics.com>
# $FreeBSD$

PORTNAME=	msgpack
PORTVERSION=	0.5.7
CATEGORIES=	devel
MASTER_SITES=	http://pecl.php.net/get/
PKGNAMEPREFIX=	pecl-
PKGNAMESUFFIX=  php5
DIST_SUBDIR=	PECL

MAINTAINER=	mb@lunetics.com
COMMENT=	PHP extension for interfacing with MessagePack

LICENSE=	BSD3CLAUSE

USES=		tar:tgz
USE_PHP=	session
USE_PHPEXT=	yes
USE_PHP_BUILD=	yes

.include <bsd.port.mk>